import { Task } from './types';

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Prepare Morning Prasad',
    description: 'Prepare prasad for morning darshan including rice, dal, and sweets',
    assignedTo: 'emp-1',
    assignedToName: 'Rajesh Kumar',
    priority: 'high',
    status: 'in-progress',
    dueDate: new Date().toISOString(),
    category: 'Kitchen',
    timeBlock: 'morning',
    estimatedHours: 4,
    actualHours: 2,
    linkedWorkflowId: 'workflow-1',
    linkedWorkflowName: 'Daily Prasad Preparation',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'Clean Main Hall',
    description: 'Deep cleaning of main hall before evening aarti',
    assignedTo: 'emp-2',
    assignedToName: 'Priya Sharma',
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    category: 'Maintenance',
    timeBlock: 'afternoon',
    estimatedHours: 2,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Setup Sound System',
    description: 'Setup and test sound system for evening aarti',
    assignedTo: 'emp-3',
    assignedToName: 'Amit Patel',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    category: 'Operations',
    timeBlock: 'evening',
    estimatedHours: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-4',
    title: 'Review Inventory Stock',
    description: 'Review and update inventory levels for perishable items',
    assignedTo: 'emp-4',
    assignedToName: 'Sneha Reddy',
    priority: 'medium',
    status: 'completed',
    dueDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    category: 'Inventory',
    timeBlock: 'morning',
    estimatedHours: 3,
    actualHours: 2.5,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-5',
    title: 'Night Security Rounds',
    description: 'Conduct security rounds of temple premises',
    assignedTo: 'emp-5',
    assignedToName: 'Vikram Singh',
    priority: 'high',
    status: 'pending',
    dueDate: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    category: 'Security',
    timeBlock: 'night',
    estimatedHours: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

