import { Volunteer, Duty } from './types';

export const mockVolunteers: Volunteer[] = [
  {
    id: 'vol-1',
    name: 'Krishna Das',
    email: 'krishna.das@example.com',
    phone: '+91 98765 43210',
    volunteerId: 'VOL001',
    status: 'active',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    totalHours: 45,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vol-2',
    name: 'Radha Devi',
    email: 'radha.devi@example.com',
    phone: '+91 98765 43211',
    volunteerId: 'VOL002',
    status: 'temporary',
    eventId: 'event-2',
    eventName: 'Navratri Celebration',
    totalHours: 20,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vol-3',
    name: 'Gopal Sharma',
    email: 'gopal.sharma@example.com',
    phone: '+91 98765 43212',
    volunteerId: 'VOL003',
    status: 'active',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    totalHours: 30,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vol-4',
    name: 'Lakshmi Narayan',
    email: 'lakshmi.narayan@example.com',
    phone: '+91 98765 43213',
    volunteerId: 'VOL004',
    status: 'active',
    eventId: 'event-3',
    eventName: 'Holi Celebration',
    totalHours: 60,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vol-5',
    name: 'Sita Ram',
    email: 'sita.ram@example.com',
    phone: '+91 98765 43214',
    volunteerId: 'VOL005',
    status: 'active',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    totalHours: 35,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vol-6',
    name: 'Hanuman Prasad',
    email: 'hanuman.prasad@example.com',
    phone: '+91 98765 43215',
    volunteerId: 'VOL006',
    status: 'inactive',
    eventId: 'event-2',
    eventName: 'Navratri Celebration',
    totalHours: 15,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vol-7',
    name: 'Durga Devi',
    email: 'durga.devi@example.com',
    phone: '+91 98765 43216',
    volunteerId: 'VOL007',
    status: 'active',
    eventId: 'event-3',
    eventName: 'Holi Celebration',
    totalHours: 50,
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'vol-8',
    name: 'Shiva Kumar',
    email: 'shiva.kumar@example.com',
    phone: '+91 98765 43217',
    volunteerId: 'VOL008',
    status: 'temporary',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    totalHours: 10,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockDuties: Duty[] = [
  {
    id: 'duty-1',
    volunteerId: 'vol-1',
    volunteerName: 'Krishna Das',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    what: 'Manage prasad distribution',
    where: 'Main Hall',
    when: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'duty-2',
    volunteerId: 'vol-2',
    volunteerName: 'Radha Devi',
    eventId: 'event-2',
    eventName: 'Navratri Celebration',
    what: 'Assist with decorations',
    where: 'Temple Premises',
    when: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'duty-3',
    volunteerId: 'vol-3',
    volunteerName: 'Gopal Sharma',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    what: 'Crowd management',
    where: 'Entrance Gate',
    when: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'duty-4',
    volunteerId: 'vol-4',
    volunteerName: 'Lakshmi Narayan',
    eventId: 'event-3',
    eventName: 'Holi Celebration',
    what: 'Sound system setup',
    where: 'Main Stage',
    when: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'duty-5',
    volunteerId: 'vol-5',
    volunteerName: 'Sita Ram',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    what: 'Parking management',
    where: 'Parking Area',
    when: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'duty-6',
    volunteerId: 'vol-7',
    volunteerName: 'Durga Devi',
    eventId: 'event-3',
    eventName: 'Holi Celebration',
    what: 'Food preparation',
    where: 'Kitchen',
    when: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'duty-7',
    volunteerId: 'vol-1',
    volunteerName: 'Krishna Das',
    eventId: 'event-1',
    eventName: 'Diwali Festival 2024',
    what: 'Cleanup after event',
    where: 'Main Hall',
    when: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'scheduled',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

